from chapter import Chapter

ch2 = Chapter(
    title = "Chapter 2"
    ,longsummary = "In the second chapter of The Wizard of Oz, Dorothys house lands in the magical Land of Oz, crushing the Wicked Witch of the East. Dorothy is greeted by the Munchkins, who thank her for freeing them from the witchs tyranny. Glinda, the Good Witch of the North, arrives and advises Dorothy to seek the assistance of the Wizard of Oz in order to return home to Kansas. Glinda also gives Dorothy the silver shoes that belonged to the Wicked Witch of the East, which possess magical powers. Dorothy sets off on her journey down the Yellow Brick Road to find the Wizard, accompanied by the Scarecrow she encounters along the way. This chapter marks the beginning of Dorothys quest in the strange and enchanting land of Oz."
    , shortsummary = "In chapter 2 of The Wizard of Oz, Dorothys house lands in Oz, killing the Wicked Witch of the East. The Munchkins thank her, and Glinda advises her to seek the Wizard of Ozs help to return home. Dorothy starts her journey with the Scarecrow down the Yellow Brick Road."
    , paragraphs = [
        "She was awakened by a shock, so sudden and severe that if Dorothy had not been lying on the soft bed she might have been hurt. As it was, the jar made her catch her breath and wonder what had happened; and Toto put his cold little nose into her face and whined dismally. Dorothy sat up and noticed that the house was not moving; nor was it dark, for the bright sunshine came in at the window, flooding the little room. She sprang from her bed and with Toto at her heels ran and opened the door.",
        "The little girl gave a cry of amazement and looked about her, her eyes growing bigger and bigger at the wonderful sights she saw.The cyclone had set the house down very gently--for a cyclone--in the midst of a country of marvelous beauty. There were lovely patches of greensward all about, with stately trees bearing rich and luscious fruits. Banks of gorgeous flowers were on every hand, and birds with rare and brilliant plumage sang and fluttered in the trees and bushes. A little way off was a small brook, rushing and sparkling along between green banks, and murmuring in a voice very grateful to a little girl who had lived so long on the dry, gray prairies.",
        "While she stood looking eagerly at the strange and beautiful sights, she noticed coming toward her a group of the queerest people she had ever seen. They were not as big as the grown folk she had always been used to; but neither were they very small. In fact, they seemed about as tall as Dorothy, who was a well-grown child for her age, although they were, so far as looks go, many years older.",
        "Three were men and one a woman, and all were oddly dressed. They wore round hats that rose to a small point a foot above their heads, with little bells around the brims that tinkled sweetly as they moved. The hats of the men were blue; the little womans hat was white, and she wore a white gown that hung in pleats from her shoulders. Over it were sprinkled little stars that glistened in the sun like diamonds. The men were dressed in blue, of the same shade as their hats, and wore well-polished boots with a deep roll of blue at the tops. The men, Dorothy thought, were about as old as Uncle Henry, for two of them had beards. But the little woman was doubtless much older. Her face was covered with wrinkles, her hair was nearly white, and she walked rather stiffly.",
        "When these people drew near the house where Dorothy was standing in the doorway, they paused and whispered among themselves, as if afraid to come farther. But the little old woman walked up to Dorothy, made a low bow and said, in a sweet voice: You are welcome, most noble Sorceress, to the land of the Munchkins. We are so grateful to you for having killed the Wicked Witch of the East, and for setting our people free from bondage.",
        "Dorothy listened to this speech with wonder. What could the little woman possibly mean by calling her a sorceress, and saying she had killed the Wicked Witch of the East? Dorothy was an innocent, harmless little girl, who had been carried by a cyclone many miles from home; and she had never killed anything in all her life.",
        "But the little woman evidently expected her to answer; so Dorothy said, with hesitation, You are very kind, but there must be some mistake. I have not killed anything. Your house did, anyway, replied the little old woman, with a laugh, and that is the same thing. See! she continued, pointing to the corner of the house. There are her two feet, still sticking out from under a block of wood.",
        "Dorothy looked, and gave a little cry of fright. There, indeed, just under the corner of the great beam the house rested on, two feet were sticking out, shod in silver shoes with pointed toes. Oh, dear! Oh, dear! cried Dorothy, clasping her hands together in dismay. The house must have fallen on her. Whatever shall we do?",
        "There is nothing to be done, said the little woman calmly. But who was she? asked Dorothy. She was the Wicked Witch of the East, as I said, answered the little woman. She has held all the Munchkins in bondage for many years, making them slave for her night and day. Now they are all set free, and are grateful to you for the favor.",
        "Who are the Munchkins? inquired Dorothy. They are the people who live in this land of the East where the Wicked Witch ruled. Are you a Munchkin? asked Dorothy. No, but I am their friend, although I live in the land of the North. When they saw the Witch of the East was dead the Munchkins sent a swift messenger to me, and I came at once. I am the Witch of the North. Oh, gracious! cried Dorothy. Are you a real witch? Yes, indeed, answered the little woman. But I am a good witch, and the people love me. I am not as powerful as the Wicked Witch was who ruled here, or I should have set the people free myself."
    ]
    , questions  =[
        [
         "Who welcomed Dorothy to the land of the Munchkins?",
         "Exactly! The Witch of the North",
         "Well actually, it was the Witch of the North who welcomed Dorothy"
        ],[
         "What was unusual about the hats worn by the people Dorothy encountered?",
         "Right on! The hats had little bells around the brims that tinkled sweetly as they moved.",
         "The hats had little bells around the brims, not feathers or flowers."
        ],[
         "What did Dorothy find sticking out from under the corner of the house?",
         "Exactly, Two feet shod in silver shoes with pointed toes.",
         "It was two feet shod in silver shoes with pointed toes that Dorothy found sticking out from under the corner of the house, not just any shoes."
        ],
    ]
)